# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PostCard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # this is very important to have!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # Pods for PostCard
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

#  pod 'react-native-config', :path => '../node_modules/react-native-config'

  # pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

#  pod 'react-native-shake-event', :path => '../node_modules/react-native-shake-event'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'


  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'MerryPhotoViewer', :path => '../node_modules/@merryjs/photo-viewer'

  pod 'NYTPhotoViewer'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

end

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
